version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.15.3
      - image: circleci/mongo:4.2.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  lint_test:
    jobs:
      - lint
      - test