/* eslint-disable no-await-in-loop */
const fancy = require('fancy-log');
const { db } = require('./index');

const benchmarkDB = async (dbConn) => {
  const conn = await dbConn;
  fancy.info('tests starting...');

  const stocks = [
    'PN93O',
    'TQ9G2',
    'BZTWU',
    'WG6J9',
    'PM2KO',
    '9BJW5',
    '2PEQ3',
    'I32R1',
    'JD6Z0',
    'SMJP5',
    'RRPF3',
    'GPE0Q',
    'PEUMC',
    'AF155',
    'BUF6F',
    '5AIKJ',
    'DQQ7T',
    'Y0TJW',
    '5B2S9',
    'R8KH7',
    'USHEE',
    'YQKWS',
    '3GOP0',
    'ZK45M',
    'RFFA0',
    'QZ8L7',
    '9ZI34',
    'KV9FW',
    'BP8RF',
    'WAPOQ',
    'IWJGL',
    'UTR5O',
    'SK6G2',
    'H9Q9K',
    'ONCDF',
    'Z9CQ8',
    'RDFMU',
    '3J2WX',
    '2KFEE',
    '2TUUW',
    '3T6JQ',
    'F393G',
    'G03FU',
    'DWURV',
    'HRBTD',
    'HRBTD',
    'KSH0G',
    'FW9YZ',
    'RH5BA',
    'DBQ6H',
    '6X64V',
    'TW92J',
    '2OUUX',
    '75BK0',
    'VRUH4',
    'BJKXX',
    'SLXRE',
    'SAF98',
    '4QZGK',
    'VSRTQ',
    '7I5AR',
    'SIBNZ',
    'VZ1JE',
    'GIT7P',
    'JCQT0',
    '7QAXJ',
    '5AWLB',
    'R6BH9',
    'RA08G',
    'RBW8Y',
    'YBCPH',
    'BVNY6',
    'I0TNO',
    'KVED5',
    'FFA66',
    '9X4ZQ',
    'OAMQY',
    'S5PJV',
    '3S64I',
    'SFW2E',
    'TXUD8',
    'ALYLW',
    'AWLQ5',
    'OKSP2',
    'XGUKR',
    'NZMW0',
    '4GM4B',
    '9PFJT',
    'E0LU3',
    'Z32LA',
    '6YRUL',
    'TV09Q',
    'NYIUP',
    'EGRFK',
    'MPV7F',
    'R9GTT',
    'CSTIV',
    'J7R1O',
    'M3CNP',
    'HIC18',
    'L6MNB',
    '1CRJX',
    'MD35X',
    'D5SMU',
    'YAUD7',
    '63NH2',
    'TK9GN',
    'CK2F6',
    'HC4PV',
    'OPOHE',
    '8TOAW',
    '81T2M',
    '24UF9',
    '0FIGA',
    'E9CQ1',
    '6ZZ9V',
    'MR358',
    'TB8LN',
    '7X7ZA',
    'WL2ET',
    '9HV2H',
    '427J7',
    'YKOBD',
    'NUMGP',
    'OP0CP',
    'SJVAK',
    'KEMLW',
    'LUZNF',
    '1TYQD',
    'GN3R6',
    'HPBQC',
    'G2FGJ',
    'K0RX3',
    'WMAVN',
    'UH61D',
    'H87JZ',
    'R3ZVY',
    '6KG3U',
    '8FODR',
    'LZSOU',
    '8H17M',
    '6BVQN',
    'B8YY4',
    'T044O',
    '3IDX1',
    '1663H',
    'G95ZG',
    'Y60OR',
    '49ILY',
    '05MIH',
    'XADCV',
    '2TN0U',
    'YAITX',
    'G9ITO',
    '344IR',
    'YTQRP',
    '9S74A',
    'FSWMJ',
    'M08LF',
    'QX49C',
    'NURZC',
    'PMMMU',
    '2WCER',
    'YX9AU',
    'P3QDG',
    '6OUB9',
    'EAFJW',
    'UMVXD',
    'K40RO',
    'R1EYZ',
    'ZJBUI',
    'DQ4JR',
    'Z3H06',
    'PKP4O',
    'LZL4Y',
    'WTC07',
    '3MMGW',
    'ZSEU8',
    'ISZ00',
    'XGSKR',
    'FG0I1',
    'IOML0',
    'S18L7',
    'Z3HJ7',
    'T9E64',
    'QSD4S',
    'W2BP9',
    'J69B3',
    'PDD7S',
    'CIBN8',
    'CUALP',
    '7C3WC',
    'Z6TOI',
    'D6C4R',
    '628EC',
    'J0JZZ',
    'V5U9T',
    '6ESNG',
    'QDO5H',
    'EEWKA',
    'NAAC9',
  ];

  const queriesData = [
    ['1D', " AND ts > '2019-12-30'"],
    ['1W', " AND ts > '2019-12-24' AND extract_min(ts) IN (0, 10, 20, 30, 40, 50)"],
    ['1M', " AND ts > '2019-11-30' AND extract_min(ts) = 0"],
    ['3M', " AND ts > '2019-09-30' AND extract_min(ts) = 0"],
    ['1Y', " AND extract_hour(ts) = 17 AND extract_min(ts) = 0 AND ts > '2018-12-31'"],
    ['5Y', " AND extract_dow(ts) = 1 AND extract_hour(ts) = 17 AND extract_min(ts) = 0 AND ts > '2014-12-31'"],
  ];

  for (let i = 0; i < queriesData.length; i += 1) {
    const queryData = queriesData[i];
    const stock = stocks[Math.floor(Math.random() * 200)];

    try {
      const query = `SELECT ts,price FROM prices WHERE stock_symbol='${stock}'${queryData[1]};`;
      let start = process.hrtime();
      const res = await conn.query(query);
      const end = process.hrtime(start);
      fancy.info(`${queryData[0]} query time first exec: ${end[1] / 1000000}ms`, `${res.rows.length} rows returned`);

      let sum = 0;
      const runs = 3;
      for (let j = 0; j < runs; j += 1) {
        start = process.hrtime();
        await conn.query(query);
        sum += process.hrtime(start)[1];
      }
      fancy.info(`${queryData[0]} query time next ${runs} avg: ${((sum / runs) / 1000000).toFixed(6)}ms`);
    } catch (error) {
      fancy.error(error);
    }
  }


  fancy.info('...tests complete');
  conn.end();
};

benchmarkDB(db).catch(fancy);
